rootProject.name = 'oracle-soa-instrumentation'
include 'oracle-cloud-runtime'
include 'oracle-as-scheduler'
include 'oracle-webservices-disi'
include 'oracle-fmw-wsserver'
include 'fabric-runtime'
include 'oracle-soa-adapters'
include 'jca-binding'
include 'bpm-services'
include 'soa-jmsadapter'
include 'orabpel'
